version: '3.1'
name: odoo_15
services:
  web:
    image: odoo:15.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    command: odoo --limit-time-real=100000 --log-handler=odoo.tools.convert:DEBUG
      
  db:
    image: postgres:12.4
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5432:5432"
    volumes:
      - 'odoo-db-data:/var/lib/postgresql/data'

volumes:
  odoo-web-data:
  odoo-db-data:
